const lifetimeLyric = {
    4: "Oh, darlin', ",
    7:"there's not much that you can say",
    10:"To stop me from fallin' in ",
    15:"like I am",
    19:"Oh, darlin',",
    22:"even waves can't wash away",
    27:"Our names in the sand, ",
    30:"never could, never can",
  
    35:"You are my everything, ",
    38:"I'd give up everything",
    42:"Show me the darkest parts",
    44: "of your heart,",
    46:"I ain't gonna run",
    50:"Every dance is slow,",
    54:"every kiss is woah",
    58:"They say you know when you know, well, I know,",
    62:"I know you're the one",
  
    66:"Some people bring you a million blessings",
    70:"Some people teach you a million lessons",
    74:"All that I lеarned, ",
    76:"it wasn't my turn, ",
    79:"it wasn't the right time",
    82:"Somе people come in your life for a reason",
    86:"Others they come in your life for a season",
    91:"But, baby, you are a lifetime",
  
    99:"Oh, darlin', ",
    102:"there's no word that can describe",
    106:"The way that I feel, tonight",
    115:"Oh, darlin', ",
    118:"I would walk that broken road",
    123:"Time and time again if it led me to your hello",
  
    130:"You are my everything, ",
    134:"I'd give up everything",
    138:"Show me the darkest parts of your heart,",
    142:"I ain't gonna run",
    146:"Every dance is slow, ",
    151:"every kiss is woah",
    155:"They say you know when you know, well, I know, ",
    158:"I know you're the one",
  
    162:"Some people bring you a million blessings",
    167:"Some people teach you a million lessons",
    171:"All that I learned, it wasn't my turn, it wasn't the right time",
    180:"Some people come in your life for a reason",
    183:"Others they come in your life for a season",
    187:"But, baby, you are a lifetime",
  
    195:"Baby, you are a lifetime",
  };
export const lyrics = [lifetimeLyric, []]