const lifetimeLyric = {
    4: "Oh, darlin', ",
    7:"there's not much that you can say",
    10:"To stop me from fallin' in ",
    15:"like I am",
    19:"Oh, darlin',",
    22:"even waves can't wash away",
    27:"Our names in the sand, ",
    30:"never could, never can",
  
    35:"You are my everything, ",
    38:"I'd give up everything",
    42:"Show me the darkest parts",
    44: "of your heart,",
    46:"I ain't gonna run",
    50:"Every dance is slow,",
    54:"every kiss is woah",
    58:"They say you know when you know, well, I know,",
    62:"I know you're the one",
  
    66:"Some people bring you a million blessings",
    70:"Some people teach you a million lessons",
    74:"All that I lеarned, ",
    76:"it wasn't my turn, ",
    79:"it wasn't the right time",
    82:"Somе people come in your life for a reason",
    86:"Others they come in your life for a season",
    91:"But, baby, you are a lifetime",
  
    99:"Oh, darlin', ",
    102:"there's no word that can describe",
    106:"The way that I feel, tonight",
    115:"Oh, darlin', ",
    118:"I would walk that broken road",
    123:"Time and time again if it led me to your hello",
  
    130:"You are my everything, ",
    134:"I'd give up everything",
    138:"Show me the darkest parts of your heart,",
    142:"I ain't gonna run",
    146:"Every dance is slow, ",
    151:"every kiss is woah",
    155:"They say you know when you know, well, I know, ",
    158:"I know you're the one",
  
    162:"Some people bring you a million blessings",
    167:"Some people teach you a million lessons",
    171:"All that I learned, it wasn't my turn, it wasn't the right time",
    180:"Some people come in your life for a reason",
    183:"Others they come in your life for a season",
    187:"But, baby, you are a lifetime",
  
    195:"Baby, you are a lifetime",
  };
  const pg = {
  16: "Menurutmu, berapa lama",
  20:"lagi kau kan mencintaiku?",
  25:"Menurutmu, apa yang", 
  29:"bisa terjadi dalam sewindu?",
  34:"Bukan apa, hanya bersiap,", 
  38:"tak ada yang tahu, aku takut",
  43:"Tak pernah ada yang lama ",
  47:"menungguku sejak dulu",
  52: "Yang terjadi ",
  57: "sebelumnya",
  61:"Semua orang ",
  65:"takut padaku, wo-oh-oh",
  71:"Memang tidak mudah",
  80:"Mencintai diri ini",
  90:"Namun, aku berjanji",
  98:"Akan mereda, wo-oh-oh,", 
  103:"seperti semestinya",
  108:"Menurutmu, apa benar", 
  112:"saat ini kau masih mencintaiku?",
  116:"Menurutmu, apa yang ",
  121:"bisa dicinta dari diriku?",
  126:"Bukan apa, hanya bersiap, ",
  130:"tak ada yang tahu, aku takut",
  135:"Tak pernah ada yang lama ",
  138:"menungguku sejak dulu",
  144:"Yang terjadi sebelumnya",
  152:"Semua orang takut padaku, wo-oh-oh",
  162:"Panggil aku",
  167:"Perempuan gila",
  172:"Hantu berkepala",
  176:"Keji membunuh kasihnya",
  181:"Penuh ganggu",
  185:"Di dalam jiwanya",
  190:"Sambil penuh cinta",
  195:"Diam-diam berusaha",
  199:"S'lalu tahu",
  203:"Akan ditinggalkan",
  209:"Namun, demi Tuhan",
  212:"Aku berusaha",
  217:"Memang ",
  221:"tidak mudah",
  226:"Mencintai diri ini",
  235:"Namun, aku berjanji",
  244:"Akan mereda ",
  248:"seperti semestinya, uh-hu-uh",
  255:"(Memang tidak mudah)",
  263:"(Mencintai diri ini)",
  272:"(Namun, aku berjanji)",
  281:"(Akan mereda seperti semestinya)",
}
export const lyrics = [lifetimeLyric, pg];